draw_set_halign(fa_center);
draw_set_valign(0);
draw_set_color (c_white);
draw_set_font (fnt_title);
draw_text (room_width/2, room_height/10, "Creditos");
draw_set_font (fnt_title);
draw_text (room_width/2, room_height/7, "Sprites");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/5, "Gracias a https://opengameart.org/");
draw_set_font (fnt_title);
draw_text (room_width/2, room_height/4.3, "Musica");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/3.5, "Gracias a https://freesound.org/");
draw_set_font (fnt_title);
draw_text (room_width/2, room_height/3, "Desarrollado");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/2.5, "Henry Rojas Douglas");
draw_set_font (fnt_title);
draw_text (room_width/2, room_height/2, "Agradecimientos");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/1.6, "GABRIEL MORERA CORDOBA");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/1.5, "CARLOS CHACON CHINCHILLA");
draw_set_font (fnt_instructions);
draw_text (room_width/2, room_height/1.4, "YENORI CARBALLO VALVERDE");